spring:
  application:
    name: stock-service
  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8082}

rabbitmq:
  queue:
    order:
      name: order-queue

  exchange:
    order:
      name: order-exchange

  routing:
    order:
      name: order-routing