spring:
  application:
    name: rabbitmq-tutorial

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  queue:
    name: "javaguides"

  exchange:
    name: "javaguides_exchange"

  routing:
    key: "javaguides_routingKey"